name: Build Info

on:
  push:
  workflow_dispatch:

jobs:
  Marketplaces:
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie kodu
        uses: actions/checkout@v4

      - name: Wylistowanie zawartości
        run: ls -la

      - name: Pobranie node'a
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Sprawdzenie wersji node'a
        run: node --version