name: Deploy

on:
  push:
    branches: [ main, 'feature/**' ]
    paths-ignore: [ 'docs/**' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: [ { run: echo "testy..." } ]

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps: [ { run: echo "Wdrażam aplikację" } ]