name: VARS

on:
  push:
  workflow_dispatch:

env:
  GREETING: "Cześć z Actions"

jobs:
  zmienne:
    runs-on: ubuntu-latest
    steps:
      - run: "echo '$GREETING / autor: ${{ github.actor }}'"

      - id: stamp
        run: echo "time=$(date +%s)" >> $GITHUB_OUTPUT

      - run: "echo 'Znacznik: ${{ steps.stamp.outputs.time }}'"